name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Configurar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Gerar site
        run: pnpm build

      - name: Criar arquivo .nojekyll
        run: touch ./out/.nojekyll

      - name: Enviar site pronto
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Publicar
        uses: actions/deploy-pages@v4
